version: '3.4'

services:
  db:
    image: 'mongo:4.4-bionic'
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - ./.data/mongo/:/data/db/
    ports:
      - '27017:27017'
    networks:
      - backend

  generate:
    image: 'generate-db'
    container_name: 'generate-db'
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      - STRIPE_KEY=${STRIPE_KEY}
    depends_on:
      - db
    networks:
      - backend

  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    volumes:
      - ./.data/redis/:/data/
    ports:
      - '6379:6379'
    networks:
      - backend
    command: redis-server --save 60 1 --loglevel warning

  app:
    image: 'app'
    container_name: 'app'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.bin/:/app/
      - ./config/:/app/config/
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - '8080:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge