version: '3.4'

services:
  db:
    image: 'mongo:4.4-bionic'
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=ecommerce
    volumes:
      - ./mongo-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - backend

  generate:
    image: 'hostrey/generate:main'
    container_name: 'generate'
    environment:
      - STRIPE_KEY=$STRIPE_KEY
    depends_on:
      - db
    networks:
      - backend

  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    ports:
      - '6379:6379'
    networks:
      - backend
    command: redis-server --save 60 1 --loglevel warning

  app:
    image: 'hostrey/ecommerce:main'
    container_name: 'app'
    environment:
      - STRIPE_KEY=$STRIPE_KEY
      - JWT_SECRET=$JWT_SECRET
    depends_on:
      - db
      - generate
      - redis
    ports:
      - '8080:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge