version: '3'
name: ecommerce
services:
  db:
    image: 'mongo:4.4-bionic'
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=ecommerce
    volumes:
      - ./mongo-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - backend
  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    ports:
      - '6379:6379'
    networks:
      - backend
    command: redis-server --save 60 1 --loglevel warning
  app:
    image: 'hostrey/ecommerce'
    container_name: 'app'
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge