version: '3.4'

services:
  db:
    image: 'mongo:4.4-bionic'
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - ./.data/mongo/:/data/db/
    ports:
      - '27017:27017'
    networks:
      - backend

  generate:
    image: ${DOCKER_HUB_USERNAME}/${GENERATE_IMAGE}
    container_name: ${GENERATE_IMAGE}
    environment:
      - STRIPE_KEY=${STRIPE_KEY}
    depends_on:
      - db
    networks:
      - backend

  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    volumes:
      - ./.data/redis/:/data/
    ports:
      - '6379:6379'
    networks:
      - backend
    command: redis-server --save 60 1 --loglevel warning

  app:
    image: ${DOCKER_HUB_USERNAME}/${APP_IMAGE}
    container_name: ${APP_IMAGE}
    environment:
      - STRIPE_KEY=${STRIPE_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
      - redis
    ports:
      - '8080:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge