version: '3.4'

services:
  db:
    image: 'mongo:4.4-bionic'
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - ./.data/mongo/:/data/db/
    ports:
      - '27017:27017'
    networks:
      - backend

  generate:
    image: ${DOCKER_HUB_USERNAME}/${GENERATE_IMAGE}:${TAG}
    container_name: ${GENERATE_IMAGE}
    environment:
      - STRIPE_KEY
    depends_on:
      - db
    networks:
      - backend

  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    volumes:
      - ./.data/redis/:/data/
    ports:
      - '6379:6379'
    networks:
      - backend
    command: redis-server --save 60 1 --loglevel warning

  app:
    image: ${DOCKER_HUB_USERNAME}/${BACKEND_IMAGE}:${TAG}
    container_name: ${APP_IMAGE}
    environment:
      - STRIPE_KEY
      - JWT_SECRET
      - HOST
      - PORT
      - DB_NAME
      - DB_URI
      - REDIS_URI
    depends_on:
      - db
      - generate
      - redis
    ports:
      - '8080:8080'
    networks:
      - backend

  frontend:
    image: ${DOCKER_HUB_USERNAME}/${FRONTEND_IMAGE}:${TAG}
    container_name: ${FRONTEND_IMAGE}
    depends_on:
      - app
    ports:
      - '3000:80'
    networks:
      - backend

networks:
  backend:
    driver: bridge