listen:
  type:
  bind_ip: localhost
  port: 8080
db:
  uri: mongodb://localhost:27017
  database: go_test
jwt:
  secret: jwtSecret
  accessTokenTime: 300000 # 15 minutes, 300000 for tests
  refreshTokenTime: 86400 # 60 days
redis:
  uri: localhost:6379