name: Build and Push

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker Hub Ecommerce image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hostrey/ecommerce
          tag_with_ref: true

      - name: Push to Docker Hub Generate mongodb image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: db/Dockerfile
          repository: hostrey/generate
          tag_with_ref: true

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - uses: actions/checkout@master
      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: "docker-compose.yml"
          target: "app"

      - name: Deploy ssh
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            export STRIPE_KEY="${{ secrets.STRIPE_KEY }}"
            export JWT_SECRET="${{ secrets.JWT_SECRET }}"
            
            cd app
            docker-compose -f docker-compose.yml stop
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d