name: Build and Push

on:
  push:
    branches: [main]
  pull_request:

defaults:
  build-and-push:
    name: Build Docker image and push to docker hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hostrey/ecommerce
          tag_with_ref: true